### ISSUE TITLE
Fine-Tuning on Custom Dataset  ERROR

### ISSUE THREAD

**Issue by menghan1124** [wanghao9610/OV-DINO#2]
W0801 13:10:30.540007 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1964 via signal SIGTERM
W0801 13:10:30.541715 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1965 via signal SIGTERM
W0801 13:10:30.542634 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1966 via signal SIGTERM
W0801 13:10:30.543450 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1967 via signal SIGTERM
W0801 13:10:30.543979 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1968 via signal SIGTERM
W0801 13:10:30.544477 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1969 via signal SIGTERM
W0801 13:10:30.545137 140343042021184 torch/multiprocessing/spawn.py:145] Terminating process 1970 via signal SIGTERM
Traceback (most recent call last):
  File "/workspace/OV-DINO/ovdino/./tools/train_net.py", line 329, in <module>
    launch(
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/root/miniconda3/envs/ov-dino/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 281, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/root/miniconda3/envs/ov-dino/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/ov-dino/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ov-dino/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/workspace/OV-DINO/ovdino/tools/train_net.py", line 320, in main
    do_train(args, cfg)
  File "/workspace/OV-DINO/ovdino/tools/train_net.py", line 220, in do_train
    train_loader = instantiate(cfg.dataloader.train)
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/data/build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/workspace/OV-DINO/ovdino/detrex/data/datasets/custom_ovd.py", line 320, in <lambda>
    lambda: load_coco_json(
  File "/workspace/OV-DINO/ovdino/detrex/data/datasets/custom_ovd.py", line 90, in load_coco_json
    meta.thing_classes = thing_classes
  File "/workspace/OV-DINO/ovdino/detectron2-717ab9/detectron2/data/catalog.py", line 148, in __setattr__
    assert oldval == val, (
AssertionError: Attribute 'thing_classes' in the metadata of 'custom_train_ovd_unipro' cannot be set to a different value!
['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'] != ['laptop', 'paper cups', 'spoon', 'paper', 'pen', 'mouse', 'tissue', 'inkpad', 'cup', 'glass bottle', 'winebottle', 'tissue box', 'ashtray', 'cigarette_case', 'fork', 'spoon', 'scissors', 'keyboard', 'helmet', 'knife', 'cellphone', 'bridle', 'watch', 'wallet', 'key', 'smoke', 'tissue paper']

用自己的数据集微调时报错，网上查看原因是需要detectron2注册数据集，麻烦解答下相关代码大概添加到哪里，以及相应的格式?

**Comment by wanghao9610** [comment]
@menghan1124 hello，你的问题解决了吗？如果没解决的话，可以参考这里（https://github.com/wanghao9610/OV-DINO/blob/bdf8acfe5878669b481d4bb662fe846b96a5f45d/ovdino/configs/common/data/custom_ovd.py#L17），有一些说明。或者 在这里（https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/detrex/data/datasets/register_custom_ovd.py）参考coco的格式添加你的数据集信息。

**Comment by menghan1124** [comment]
> @menghan1124 hello，你的问题解决了吗？如果没解决的话，可以参考[custom_ovd.py](https://github.com/wanghao9610/OV-DINO/blob/bdf8acfe5878669b481d4bb662fe846b96a5f45d/ovdino/configs/common/data/custom_ovd.py#L17)，有一些说明。或者 [register_custom_ovd.py](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/detrex/data/datasets/register_custom_ovd.py)，参考coco的格式添加你的数据集信息。

解决了
