### ISSUE TITLE
请问一下运行finetune的时候，这个问题怎么解决呢？

### ISSUE THREAD

**Issue by CachCheng** [wanghao9610/OV-DINO#22]
/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "./tools/train_net.py", line 335, in <module>
    args=(args,),
  File "/meta/cash/llm/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 79, in launch
    daemon=False,
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/utils/hub.py", line 429, in cached_file
    local_files_only=local_files_only,
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1286, in hf_hub_download
    "Cannot find the requested files in the disk cache and"
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable hf.co look-ups and downloads online, set 'local_files_only' to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/meta/cash/llm/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/meta/cash/llm/OV-DINO/ovdino/tools/train_net.py", line 320, in main
    do_train(args, cfg)
  File "/meta/cash/llm/OV-DINO/ovdino/tools/train_net.py", line 210, in do_train
    model = instantiate(cfg.model)
  File "/meta/cash/llm/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/meta/cash/llm/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/meta/cash/llm/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
  File "/meta/cash/llm/OV-DINO/ovdino/detrex/modeling/language_backbone/bert.py", line 99, in __init__
    self.tokenizer = BERTTokenizer(**tokenizer_cfg)
  File "/meta/cash/llm/OV-DINO/ovdino/detrex/modeling/language_backbone/bert.py", line 40, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 659, in from_pretrained
    pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
    _commit_hash=commit_hash,
  File "/home/ahs/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/utils/hub.py", line 453, in cached_file
    f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this file, couldn't find it in the"
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by wanghao9610** [comment]
The same issue, refer to the issue #18.
