### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by JayChouDemo** [wanghao9610/OV-DINO#35]
**The following error occurred while fine-tuning the dataset I built myself. RuntimeError: CUDA error: device-side assert triggered。**
The error message is as follows:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 321, in main
    do_train(args, cfg)
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 289, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 100, in run_step
    loss_dict = self.model(data)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 254, in forward
    self.prepare_for_cdn(
  File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 512, in prepare_for_cdn
    padding_label = torch.zeros(pad_size, hidden_dim).cuda()
RuntimeError: CUDA error: device-side assert triggered
**Transferring some operations of the ovdino model to the CPU, it was found that the index exceeded the bounds during the self.label_denc process**
**modify ovdino.py**L94，self.label_enc = nn.Embedding(num_classes, embed_dim) 为self.label_enc = nn.Embedding(num_classes+1000, embed_dim)
Error changed to：
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 321, in main
    do_train(args, cfg)
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 289, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 100, in run_step
    loss_dict = self.model(data)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 281, in forward
    ) = self.transformer(
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/dino_transformer.py", line 823, in forward
    enc_outputs_class = self.decoder.class_embed[self.decoder.num_layers](
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/big_model/OV-DINO/ovdino/detrex/layers/class_embed.py", line 34, in forward
    lang_embeds_proj = self.lang_embed_proj(lang_embeds / 2.0)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (298x1536 and 768x256)

**Comment by JayChouDemo** [comment]
![Uploading mmexport1725015129486.png…]()

**Comment by JayChouDemo** [comment]
![mmexport1725015129486](https://github.com/user-attachments/assets/97861bf6-2cf1-41b9-8d39-ffb9eb2ad248)

**Comment by wanghao9610** [comment]
> **The following error occurred while fine-tuning the dataset I built myself. RuntimeError: CUDA error: device-side assert triggered。** The error message is as follows: Traceback (most recent call last): File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap fn(i, *args) File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 126, in _distributed_worker main_func(*args) File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 321, in main do_train(args, cfg) File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 289, in do_train trainer.train(start_iter, cfg.train.max_iter) File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/train_loop.py", line 149, in train self.run_step() File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 100, in run_step loss_dict = self.model(data) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward output = self._run_ddp_forward(*inputs, **kwargs) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward return module_to_run(*inputs[0], **kwargs[0]) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 254, in forward self.prepare_for_cdn( File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 512, in prepare_for_cdn padding_label = torch.zeros(pad_size, hidden_dim).cuda() RuntimeError: CUDA error: device-side assert triggered **Transferring some operations of the ovdino model to the CPU, it was found that the index exceeded the bounds during the self.label_denc process** **modify ovdino.py**L94，self.label_enc = nn.Embedding(num_classes, embed_dim) 为self.label_enc = nn.Embedding(num_classes+1000, embed_dim) Error changed to： File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 321, in main do_train(args, cfg) File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 289, in do_train trainer.train(start_iter, cfg.train.max_iter) File "/media/213HomeDir/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/train_loop.py", line 149, in train self.run_step() File "/home/big_model/OV-DINO/ovdino/tools/train_net.py", line 100, in run_step loss_dict = self.model(data) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward output = self._run_ddp_forward(*inputs, **kwargs) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward return module_to_run(*inputs[0], **kwargs[0]) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 281, in forward ) = self.transformer( File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/dino_transformer.py", line 823, in forward enc_outputs_class = self.decoder.class_embed[self.decoder.num_layers]( File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/big_model/OV-DINO/ovdino/detrex/layers/class_embed.py", line 34, in forward lang_embeds_proj = self.lang_embed_proj(lang_embeds / 2.0) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward return F.linear(input, self.weight, self.bias) RuntimeError: mat1 and mat2 shapes cannot be multiplied (298x1536 and 768x256)

Check the shape of class_embed in [L823](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/projects/ovdino/modeling/dino_transformer.py#L823) to ensure its shape is [batch_size, num_classes, embedd_dim].

**Comment by JayChouDemo** [comment]
I replaced it with another dataset of 23 classes and it can be trained normally now. However, this bug appeared during the verification phase:
File "/media/disk6/213HomeDir/nsl/code/big_model/OV-DINO/ovdino/detectron2-717ab9/detectron2/evaluation/evaluator.py", line 158, in inference_on_dataset
    outputs = model(inputs)
  File "/root/miniconda3/envs/ovdino/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/big_model/OV-DINO/ovdino/projects/ovdino/modeling/ovdino.py", line 215, in forward
    text_embed = torch.stack(
RuntimeError: stack expects each tensor to be equal size, but got [32, 768] at entry 0 and [24, 768] at entry 1

**Comment by wanghao9610** [comment]
It probably is the same error, the num_classes has not been set correctly.

**Comment by JayChouDemo** [comment]
I printed it, is that correct?
![Uploading 微信图片_20240902192512.png…]()
![Uploading 微信图片_20240902192546.png…]()

**Comment by JayChouDemo** [comment]
![mmexport1725276586954](https://github.com/user-attachments/assets/01eae7e0-8dc1-434d-a22b-a6bed77c8f7f)
![mmexport1725276588199](https://github.com/user-attachments/assets/dfa91b20-c420-43f8-ace4-2ee6774fc99f)

**Comment by wanghao9610** [comment]
Actually, you missed the batch_size at dimension 0. You can simply convert each item into a list. I recommend you to run the COCO inference, which is correctly proved by me.
