### ISSUE TITLE
deploy issues

### ISSUE THREAD

**Issue by KONGYOUYL** [wanghao9610/OV-DINO#40]
Hello: 
        When i use demo.sh to try ovdino-sam2, i meet the huggingface error. But i have already download the model for local as readme said, that the file inits/ovdino and inits/sam2.  Can you give me some suggestions for this problem, Thanks.

        _**My bash cmd is :**_
bash scripts/demo.sh \
  projects/ovdino/configs/ovdino_swin_tiny224_bert_base_infer_demo.py \
  ../inits/ovdino/ovdino_swint_ogc-coco50.2_lvismv40.1_lvis32.9.pth \
  "wall rug floor chair sofa window" /data/xxxxx/project/OV-DINO/ovdino/demo/imgs/ /data/xxxxx/project/OV-DINO/ovdino/demo/test/

       _**My error log is** ：_
[09/07 17:14:12 detectron2]: Arguments: Namespace(config_file='projects/ovdino/configs/ovdino_swin_tiny224_bert_base_infer_demo.py', sam_config_file='/data/xxxxx/project/OV-DINO/inits/sam2/sam2_hiera_l.yaml', sam_init_checkpoint='/data/xxxxx/project/OV-DINO/inits/sam2/sam2_hiera_large.pt', webcam=False, video_input=None, input=['/data/xxxxx/project/OV-DINO/ovdino/demo/imgs/'], category_names=['wall', 'rug', 'floor', 'chair', 'sofa', 'window'], output='/data/xxxxx/project/OV-DINO/ovdino/demo/test/', min_size_test=800, max_size_test=1333, img_format='RGB', metadata_dataset='coco_2017_val', confidence_threshold=0.5, opts=['train.init_checkpoint=/data/xxxxx/project/OV-DINO/inits/ovdino/ovdino_swint_ogc-coco50.2_lvismv40.1_lvis32.9.pth', 'model.num_classes=6'])
projects/ovdino/configs/ovdino_swin_tiny224_bert_base_infer_demo.py
/usr/local/lib/python3.10/dist-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1848, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable hf.co look-ups and downloads online, set 'local_files_only' to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/xxxxx/project/OV-DINO/ovdino/./demo/demo.py", line 158, in <module>
    model = instantiate(cfg.model)
  File "/data/xxxxx/project/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/data/xxxxx/project/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/data/xxxxx/project/OV-DINO/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
  File "/data/xxxxx/project/OV-DINO/ovdino/./detrex/modeling/language_backbone/bert.py", line 99, in __init__
    self.tokenizer = BERTTokenizer(**tokenizer_cfg)
  File "/data/xxxxx/project/OV-DINO/ovdino/./detrex/modeling/language_backbone/bert.py", line 40, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by KONGYOUYL** [comment]
@wanghao9610

**Comment by wanghao9610** [comment]
Sorry to give response too late, you can refer this issue #32.

**Comment by KONGYOUYL** [comment]
@wanghao9610 Thank you for your response. I resolved the issue by downloading the BERT model and linking it locally in the project.
