### ISSUE TITLE
ovdino+sam conda environment ,error,  run:cd $root_dir/ovdino bash scripts/app.sh \   projects/ovdino/configs/ovdino_swin_tiny224_bert_base_infer_demo.py \   ../inits/ovdino/ovdino_swint_ogc-coco50.2_lvismv40.1_lvis32.9.pth

### ISSUE THREAD

**Issue by U201311** [wanghao9610/OV-DINO#42]

**Comment by U201311** [comment]
Traceback (most recent call last):
{'tokenizer_name': 'bert-base-uncased'}
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1848, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable hf.co look-ups and downloads online, set 'local_files_only' to False.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data/liy/keepfit/ovdino/./tools/train_net.py", line 329, in <module>
    launch(
  File "/mnt/data/liy/keepfit/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/mnt/data/liy/keepfit/ovdino/./tools/train_net.py", line 303, in main
    model = instantiate(cfg.model)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/liy/keepfit/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 67, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
              ^^^^^^^^^^^^^^
  File "/mnt/data/liy/keepfit/ovdino/detectron2-717ab9/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
           ^^^^^^^^^^
  File "/mnt/data/liy/keepfit/ovdino/detrex/modeling/language_backbone/bert.py", line 100, in __init__
    self.tokenizer = BERTTokenizer(**tokenizer_cfg)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/liy/keepfit/ovdino/detrex/modeling/language_backbone/bert.py", line 40, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 854, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 976, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liy/miniconda3/envs/ovsam/lib/python3.12/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by wanghao9610** [comment]
@U201311 You need provide more detail information to debug.

**Comment by U201311** [comment]
> @U201311 You need provide more detail information to debug.

ok, thanks, I fix it, somewrong about environment
